# Generated by Django 5.1.4 on 2025-01-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('pimage', models.ImageField(upload_to='file')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
