# Generated by Django 5.1.4 on 2025-01-20 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='ordermaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('gtotal', models.IntegerField()),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.regform')),
            ],
        ),
        migrations.CreateModel(
            name='orderchild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
                ('oid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.ordermaster')),
            ],
        ),
    ]
