# Generated by Django 5.1.4 on 2025-01-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_ordermaster_orderchild'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderchild',
            name='qty',
            field=models.IntegerField(default=0),
        ),
    ]
